package com;

/*
Question

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

1267602-Tl2SF8H7HMnCh0uXOTPBUsyaNA9liPbn5aXGGDvc

*/


import java.util.ArrayList;
import java.util.List;

public class Problem2 {

    public static void main(String[] args) {

        List<Long> longList = new ArrayList();

        longList.add(1l);
        longList.add(2l);
        long sum = 0l;

        while (sum < 4000000) {

            long one = longList.get(longList.size() - 1);
            long two = longList.get(longList.size() - 2);

            sum = one + two;
            if (sum <= 4000000) {
                longList.add(one + two);
            }

        }

        System.out.println(longList);


        Long aLong = longList.stream().filter(l -> l % 2 == 0).reduce(0l, Long::sum);
        System.out.println(aLong);


    }
}
